apiVersion: v1
appVersion: "1.10"
description: A Helm chart for registry creds
name: registry-creds
version: 1.3.0
home: https://hub.docker.com/r/upmcenterprises/registry-creds
sources:
  - https://github.com/upmc-enterprises/registry-creds
maintainers:
  - name: kir4h
    email: 1671935+kir4h@users.noreply.github.com
